from setuptools import setup, find_packages

setup(
    name='versa-speech-audio-toolkit',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[
        "audioread>=3.0.1",
        "ci-sdr>=0.0.2",
        "Cython>=3.0.10",
        "Distance>=0.1.3",
        "editdistance>=0.8.1",
        "einops>=0.8.0",
        "espnet>=202402",
        "espnet-tts-frontend>=0.0.3",
        "fast-bss-eval>=0.1.3",
        "fastdtw>=0.3.4",
        "huggingface-hub>=0.23.2",
        "hydra-core>=1.3.2",
        "idna>=3.7",
        "importlib-metadata>=4.13.0",
        "kaggle>=1.6.14",
        "kaldiio>=2.18.0",
        "lazy_loader>=0.4",
        "Levenshtein>=0.25.1",
        "librosa>=0.9.2",
        "mir-eval>=0.7",
        "omegaconf>=2.3.0",
        "onnxruntime>=1.18.0",
        "opt-einsum>=3.3.0",
        "pesq>=0.0.4",
        "protobuf>=3.20.3",
        "pypesq @ git+https://github.com/vBaiCai/python-pesq.git",
        "pysptk>=0.2.2",
        "pystoi>=0.4.1",
        "python-dateutil>=2.9.0",
        "pyworld>=0.3.4",
        "pyyaml>=6.0.1",
        "rapidfuzz>=3.9.3",
        "resampy>=0.4.3",
        "safetensors>=0.4.3",
        "scikit-learn>=1.5.0",
        "sentencepiece>=0.1.97",
        "setuptools>=69.5.1",
        "soundfile>=0.12.1",
        "speechmos>=0.0.1.1",
        "sympy>=1.12.1",
        "threadpoolctl>=3.5.0",
        "tokenizers>=0.19.1",
        "torch>=2.1.0",
        "torch-complex>=0.4.3",
        "torchaudio>=2.1.0",
        "transformers>=4.41.2",
        "espnet_model_zoo>=0.1.7",
        "discrete-speech-metrics @ git+https://github.com/Takaaki-Saeki/DiscreteSpeechMetrics.git@v1.0.1",
    ],
    author='Jiatong Shi',
    author_email='ftshijt@gmail.com',
    description='A package for versatile evaluation of speech and audio',
    url='https://github.com/shinjiwlab/versa.git',
    keywords='speech metrics',
)
