from setuptools import setup, find_packages

setup(
    name='versa-speech-audio-toolkit',
    version='0.0.1',
    packages=find_packages(),
    install_requires=[
        "audioread",
        "ci-sdr",
        "Cython",
        "Distance",
        "editdistance",
        "einops",
        "espnet",
        "espnet-tts-frontend",
        "fast-bss-eval",
        "fastdtw",
        "huggingface-hub",
        "hydra-core",
        "idna",
        "importlib-metadata",
        "kaggle",
        "kaldiio",
        "lazy_loader4",
        "Levenshtein",
        "librosa",
        "mir-eval",
        "omegaconf",
        "onnxruntime",
        "opt-einsum",
        "pesq",
        "protobuf",
        "pypesq @ git+https://github.com/vBaiCai/python-pesq.git",
        "pysptk",
        "pystoi",
        "python-dateutil",
        "pyworld",
        "pyyaml",
        "rapidfuzz",
        "resampy",
        "safetensors",
        "scikit-learn",
        "sentencepiece",
        "setuptools",
        "soundfile",
        "speechmos",
        "sympy",
        "threadpoolctl",
        "tokenizers",
        "torch",
        "torch-complex",
        "torchaudio",
        "transformers",
        "espnet_model_zoo",
        "discrete-speech-metrics @ git+https://github.com/Takaaki-Saeki/DiscreteSpeechMetrics.git@v1.0.1",
    ],
    author='Jiatong Shi',
    author_email='ftshijt@gmail.com',
    description='A package for versatile evaluation of speech and audio',
    url='https://github.com/shinjiwlab/versa.git',
    keywords='speech metrics',
)
